version: "3.9"
services:
  web:
    hostname: webserver
    build: ./web
    ports:
      - "8088:8088"
    volumes:
      - ./keys:/keys
  xssbot:
    image: leonsec/xssbot:v1
    volumes:
      - ./xssbot:/xssbot
      - ./keys:/keys
    depends_on:
      - web
    entrypoint: python2 /xssbot/bot.py
    links:
      - "web:webserver"

